import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

import { LoginPage } from '../../../main/pages/LoginPage';
import { AccountsOverviewPage } from '../../../main/pages/AccountsOverviewPage';
import { FindTransactionsPage } from '../../../main/pages/FindTransactionsPage';

const credentialsPath = path.join(
  process.cwd(),
  'test-data',
  'json',
  'LoginCredentials.json'
);

if (!fs.existsSync(credentialsPath)) {
  throw new Error(
    `Login credentials file was not found: ${credentialsPath}`
  );
}

const credentials = JSON.parse(
  fs.readFileSync(credentialsPath, 'utf-8')
);

if (!credentials.username || !credentials.password) {
  throw new Error(
    'LoginCredentials.json must contain username and password.'
  );
}

test.describe('ParaBank - Find Transactions UI', () => {

  test.beforeEach(async ({ page }) => {

    await page.goto(
      'https://parabank.parasoft.com/parabank/index.htm',
      {
        waitUntil: 'domcontentloaded'
      }
    );

    const loginPage = new LoginPage(page);

    await loginPage.login(
      credentials.username,
      credentials.password
    );

    await expect(
      page.getByRole('heading', {
        name: /Accounts Overview/i
      }).first()
    ).toBeVisible({
      timeout: 30000
    });
  });

  test('Find Transactions page should display all search options', async ({
    page
  }) => {

    await page.getByRole('link', {
      name: 'Find Transactions'
    }).click();

    const findTransactionsPage =
      new FindTransactionsPage(page);

    await expect(
      findTransactionsPage.accountDropdown
    ).toBeVisible();

    await expect(
      findTransactionsPage.transactionIdInput
    ).toBeVisible();

    await expect(
      findTransactionsPage.findByIdButton
    ).toBeVisible();

    await expect(
      findTransactionsPage.transactionDateInput
    ).toBeVisible();

    await expect(
      findTransactionsPage.findByDateButton
    ).toBeVisible();

    await expect(
      findTransactionsPage.fromDateInput
    ).toBeVisible();

    await expect(
      findTransactionsPage.toDateInput
    ).toBeVisible();

    await expect(
      findTransactionsPage.findByDateRangeButton
    ).toBeVisible();

    await expect(
      findTransactionsPage.amountInput
    ).toBeVisible();

    await expect(
      findTransactionsPage.findByAmountButton
    ).toBeVisible();
  });

  test('User should be able to search transactions by transaction ID', async ({
    page
  }) => {

    await page.getByRole('link', {
      name: 'Find Transactions'
    }).click();

    const accountsOverviewPage =
      new AccountsOverviewPage(page);

    await accountsOverviewPage.waitForAccountsToLoad();

    const accountNumber =
      await accountsOverviewPage.getFirstAccountNumber();

    const findTransactionsPage =
      new FindTransactionsPage(page);

    await findTransactionsPage.selectAccount(
      accountNumber
    );

    // Replace this with an actual transaction ID
    // once we have one generated by the application.
    const transactionId = '44113';

    await findTransactionsPage.findByTransactionId(
      transactionId
    );

    await expect(
      findTransactionsPage.transactionResultsHeading
    ).toBeVisible({
      timeout: 30000
    });
  });

  test('User should be able to search transactions by date', async ({
    page
  }) => {

    await page.getByRole('link', {
      name: 'Find Transactions'
    }).click();

    const accountsOverviewPage =
      new AccountsOverviewPage(page);

    await accountsOverviewPage.waitForAccountsToLoad();

    const accountNumber =
      await accountsOverviewPage.getFirstAccountNumber();

    const findTransactionsPage =
      new FindTransactionsPage(page);

    await findTransactionsPage.selectAccount(
      accountNumber
    );

    // Example date based on the format shown
    // by the application.
    await findTransactionsPage.findByDate(
      '09-27-2026'
    );

    await expect(
      findTransactionsPage.transactionResultsHeading
    ).toBeVisible({
      timeout: 30000
    });
  });

  test('User should be able to search transactions by date range', async ({
    page
  }) => {

    await page.getByRole('link', {
      name: 'Find Transactions'
    }).click();

    const accountsOverviewPage =
      new AccountsOverviewPage(page);

    await accountsOverviewPage.waitForAccountsToLoad();

    const accountNumber =
      await accountsOverviewPage.getFirstAccountNumber();

    const findTransactionsPage =
      new FindTransactionsPage(page);

    await findTransactionsPage.selectAccount(
      accountNumber
    );

    await findTransactionsPage.findByDateRange(
      '09-01-2026',
      '09-27-2026'
    );

    await expect(
      findTransactionsPage.transactionResultsHeading
    ).toBeVisible({
      timeout: 30000
    });
  });

  test('User should be able to search transactions by amount', async ({
    page
  }) => {

    await page.getByRole('link', {
      name: 'Find Transactions'
    }).click();

    const accountsOverviewPage =
      new AccountsOverviewPage(page);

    await accountsOverviewPage.waitForAccountsToLoad();

    const accountNumber =
      await accountsOverviewPage.getFirstAccountNumber();

    const findTransactionsPage =
      new FindTransactionsPage(page);

    await findTransactionsPage.selectAccount(
      accountNumber
    );

    await findTransactionsPage.findByAmount(
      '100'
    );

    await expect(
      findTransactionsPage.transactionResultsHeading
    ).toBeVisible({
      timeout: 30000
    });
  });
});