import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

import { LoginPage } from '../../../main/pages/LoginPage';
import { AccountsOverviewPage } from '../../../main/pages/AccountsOverviewPage';

// =========================================================
// Login Credentials
// =========================================================

const credentialsPath = path.join(
  process.cwd(),
  'test-data',
  'json',
  'LoginCredentials.json'
);

// =========================================================
// Validate Credentials File
// =========================================================

if (!fs.existsSync(credentialsPath)) {
  throw new Error(
    `Login credentials file was not found: ${credentialsPath}. ` +
    `Run Registration.spec.ts first.`
  );
}

// =========================================================
// Read Credentials Generated by Registration
// =========================================================

const credentials = JSON.parse(
  fs.readFileSync(
    credentialsPath,
    'utf-8'
  )
);

if (
  !credentials.username ||
  !credentials.password
) {
  throw new Error(
    'LoginCredentials.json must contain username and password.'
  );
}

console.log(
  `Using registered username: ${credentials.username}`
);

// =========================================================
// Accounts Overview Test Suite
// =========================================================

test.describe(
  'ParaBank - Accounts Overview',
  () => {

    // -----------------------------------------------------
    // Login before every test
    // -----------------------------------------------------

    test.beforeEach(async ({ page }) => {

      await page.goto(
        'https://parabank.parasoft.com/parabank/index.htm',
        {
          waitUntil: 'domcontentloaded'
        }
      );

      const loginPage =
        new LoginPage(page);

      await loginPage.login(
        credentials.username,
        credentials.password
      );

      await expect(
        page.getByRole(
          'heading',
          {
            name: /Accounts Overview/i
          }
        ).first()
      ).toBeVisible({
        timeout: 30000
      });
    });

    // =====================================================
    // Test 1 - Accounts Overview
    // =====================================================

    test(
      'User should be able to view Accounts Overview',
      async ({ page }) => {

        const accountsOverviewPage =
          new AccountsOverviewPage(page);

        await expect(
          accountsOverviewPage.accountsOverviewHeading
        ).toBeVisible();

        await expect(
          accountsOverviewPage.accountTable
        ).toBeVisible();
      }
    );

    // =====================================================
    // Test 2 - Account Count
    // =====================================================

    test(
      'User should have at least one account',
      async ({ page }) => {

        const accountsOverviewPage =
          new AccountsOverviewPage(page);

        await accountsOverviewPage.waitForAccountsToLoad();

        const accountCount =
          await accountsOverviewPage.getAccountCount();

        expect(
          accountCount
        ).toBeGreaterThan(0);
      }
    );

  }
);